### ISSUE TITLE
Missing sm_89

### ISSUE THREAD

**Issue by zq-chen22** [elenacliu/pytorch_cuda_driver_compatibilities#2]
Nice tool but leaving a problem.
sm_89 compute compatibility is adopted by RTX 40 versions, yet not listed.
Is it identical with sm_86?

**Comment by elenacliu** [comment]
The data is extracted from prebuilt binaries from conda via cuobjdump.

> Nice tool but leaving a problem. sm_89 compute compatibility is adopted by RTX 40 versions, yet not listed. Is it identical with sm_86?

Please refer to CUDA & PyTorch documentation.
